version: 2
jobs:
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run: |
          touch run_app.sh
          echo "export PGUSER=${PGUSER}" >> run_app.sh
          echo "export PGPASSWORD=${PGPASSWORD}" >> run_app.sh
          echo "export PGHOST=${PGHOST}" >> run_app.sh
          echo "export PGPORT=${PGPORT}" >> run_app.sh
          echo "export PGDATABASE=${PGDATABASE}" >> run_app.sh
          echo "node app.js" >> run_app.sh
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          gcloud app deploy
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master

