version: 2
jobs:
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run: |
          touch .env
          echo "export PGUSER=${PGUSER}" >> .env
          echo "export PGPASSWORD=${PGPASSWORD}" >> .env
          echo "export PGHOST=${PGHOST}" >> .env
          echo "export PGPORT=${PGPORT}" >> .env
          echo "export PGDATABASE=${PGDATABASE}" >> .env
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          gcloud app deploy
workflows:
  version: 2
  deploy:
    jobs:
      - deploy